// flow-typed signature: 23844e53b79bb8f986ed9724baed2028
// flow-typed version: <<STUB>>/feathers-mongoose_v^6.1.4/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'feathers-mongoose'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'feathers-mongoose' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'feathers-mongoose/lib/error-handler' {
  declare module.exports: any;
}

declare module 'feathers-mongoose/lib/hooks' {
  declare module.exports: any;
}

declare module 'feathers-mongoose/lib/index' {
  declare module.exports: any;
}

declare module 'feathers-mongoose/lib/service' {
  declare module.exports: any;
}

// Filename aliases
declare module 'feathers-mongoose/lib/error-handler.js' {
  declare module.exports: $Exports<'feathers-mongoose/lib/error-handler'>;
}
declare module 'feathers-mongoose/lib/hooks.js' {
  declare module.exports: $Exports<'feathers-mongoose/lib/hooks'>;
}
declare module 'feathers-mongoose/lib/index.js' {
  declare module.exports: $Exports<'feathers-mongoose/lib/index'>;
}
declare module 'feathers-mongoose/lib/service.js' {
  declare module.exports: $Exports<'feathers-mongoose/lib/service'>;
}
