module.exports = [
  {
    itemId: 1,
    name: 'Z120 Mini Stereo Speaker 2.0 [980-000514]',
    casing: '-',
    category: 'speaker',
    brand: 'logitech',
    price: 'Rp 195,000',
    picture: 'Z120 Mini Stereo Speaker 2.0 [980-000514].png',
  },
  {
    itemId: 2,
    name: 'nVidia Geforce GTX 1060 Graphics Card [6 GB/DDR5/U-6G/Dual Fan]',
    casing: 'all (mid-tower & tower)',
    category: 'VGA',
    brand: 'Igame',
    price: 'Rp 4,189,000',
    picture: 'nVidia Geforce GTX 1060 Graphics Card [6 GBDDR5U-6GDual Fan].png',
  },
  {
    itemId: 3,
    name: 'ASUS ROG Maximus VIII Hero Skylake Motherboard',
    casing: 'tower',
    category: 'motherboard',
    brand: 'Asus',
    price: 'Rp 5,230,000',
    picture: 'ASUS ROG Maximus VIII Hero Skylake Motherboard.png',
  },
  {
    itemId: 4,
    name: 'Zotac GTX 1070 nVidia Geforce VGA Card [AMP Edition/ 8GB DDR5]',
    casing: 'all (mid-tower & tower)',
    category: 'VGA',
    brand: 'Zotac',
    price: 'Rp 8,330,000',
    picture:
      'Zotac GTX 1070 nVidia Geforce VGA Card [AMP Edition 8GB DDR5].png',
  },
  {
    itemId: 5,
    name: 'ZOTAC nVidia Geforce GTX 1060 VGA Card [AMP Edition/6GB DDR5]',
    casing: 'all (mid-tower & tower)',
    category: 'VGA',
    brand: 'Zotac',
    price: 'Rp 5,500,000',
    picture: 'ZOTAC nVidia Geforce GTX 1060 VGA Card [AMP Edition6GB DDR5].png',
  },
  {
    itemId: 6,
    name: 'ZOTAC Geforce GTX 750 Ti Graphic Card [2048 MB/DDR5]',
    casing: 'all (mid-tower & tower)',
    category: 'VGA',
    brand: 'Zotac',
    price: 'Rp 1,850,000',
    picture: 'ZOTAC Geforce GTX 750 Ti Graphic Card [2048 MBDDR5].png',
  },
  {
    itemId: 7,
    name: 'Galax nVidia Geforce GTX 750 Ti EXOC VGA Card [2 GB/DDR5/Dual Fan]',
    casing: 'all (mid-tower & tower)',
    category: 'VGA',
    brand: 'Galax',
    price: 'Rp 2,010,000',
    picture:
      'Galax nVidia Geforce GTX 750 Ti EXOC VGA Card [2 GBDDR5Dual Fan].png',
  },
  {
    itemId: 8,
    name: 'ZOTAC nVidia Geforce GTX 1080 AMP Edition VGA Card [8 GB DDR5X]',
    casing: 'all (mid-tower & tower)',
    category: 'VGA',
    brand: 'zotac',
    price: 'Rp 11,099,000',
    picture:
      'ZOTAC nVidia Geforce GTX 1080 AMP Edition VGA Card [8 GB DDR5X].png',
  },
  {
    itemId: 9,
    name: 'ASUS Z170A Motherboard',
    casing: 'tower',
    category: 'motherboard',
    brand: 'asus',
    price: 'Rp 3,600,000',
    picture: 'ASUS Z170A Motherboard.png',
  },
  {
    itemId: 10,
    name:
      'Cube Gaming Weiss Black Intel PC 3 [Intel Core i5-6500/GTX 1070 8GB/16GB RAM DDR4/240GB SSD/WIFI]',
    casing: '-',
    category: 'desktop',
    brand: 'cube',
    price: 'Rp 17,389,000',
    picture:
      'Cube Gaming Weiss Black Intel PC 3 [Intel Core i5-6500GTX 1070 8GB16GB RAM DDR4240GB SSDWIFI].png',
  },
  {
    itemId: 11,
    name:
      'Raijintek Nestor Black 6 PC Desktop [Intel i5-6500 Skylake/Nvidia GTX 1060 6GB/16GB RAM/SSD 240GB/WIFI/22 Inch/Win 10]',
    casing: '-',
    category: 'desktop',
    brand: 'raijintek',
    price: 'Rp 22,598,000',
    picture:
      'Raijintek Nestor Black 6 PC Desktop [Intel i5-6500 SkylakeNvidia GTX 1060 6GB16GB RAMSSD 240GBWIFI22 InchWin 10].png',
  },
  {
    itemId: 12,
    name: 'Sandisk CZ73 Ultra Flair Flashdisk [32 GB/USB 3.0/150MB/s]',
    casing: '-',
    category: 'USB / flashdisk',
    brand: 'sandisk',
    price: 'Rp 149,000',
    picture: 'Sandisk CZ73 Ultra Flair Flashdisk [32 GBUSB 3.0150MBs].png',
  },
  {
    itemId: 13,
    name: 'SanDisk Cruzer Fit CZ33 Flashdisk [16 GB]',
    casing: '-',
    category: 'USB / flashdisk',
    brand: 'sandisk',
    price: 'Rp 109,000',
    picture: 'SanDisk Cruzer Fit CZ33 Flashdisk [16 GB].png',
  },
  {
    itemId: 14,
    name:
      'AMD Vishera FX-8350 Prosesor [4.0 Ghz/Cache 8 MB/125 watt/AM3+/8 Core]',
    casing: 'all (mid-tower & tower)',
    category: 'prosesor',
    brand: 'amd',
    price: 'Rp 2,835,000',
    picture:
      'AMD Vishera FX-8350 Prosesor [4.0 GhzCache 8 MB125 wattAM3+8 Core].png',
  },
  {
    itemId: 15,
    name:
      'Raijintek Nestor Desktop PC - Black [Intel i7-6700K Skylake/Nvidia GTX 1060 6GB/16GB RAM/SSD 480GB/WiFi/Win 10]',
    casing: '-',
    category: 'desktop PC',
    brand: 'raijintek',
    price: 'Rp 21,185,000',
    picture:
      'Raijintek Nestor Desktop PC - Black [Intel i7-6700K SkylakeNvidia GTX 1060 6GB16GB RAMSSD 480GBWiFiWin 10].png',
  },
  {
    itemId: 16,
    name: 'Zotac nVidia Geforce GTX 1070 AMP Extreme Graphic Card [8 GB/DDR5]',
    casing: 'all (mid-tower & tower)',
    category: 'vga',
    brand: 'zotac',
    price: 'Rp 8,760,000',
    picture:
      'Zotac nVidia Geforce GTX 1070 AMP Extreme Graphic Card – [8 GBDDR5].png',
  },
  {
    itemId: 17,
    name: 'ASUS Z170i Pro Gaming Motherboard [Mini itx]',
    casing: 'all (mid-tower & tower)',
    category: 'motherboard',
    brand: 'asus',
    price: 'Rp 3,830,000',
    picture: 'ASUS Z170i Pro Gaming Motherboard [Mini itx].png',
  },
  {
    itemId: 18,
    name: 'Galax GTX 1050 Ti OC Series Graphic Card [4GB DDR5]',
    casing: 'all (mid-tower & tower)',
    category: 'vga',
    brand: 'galax',
    price: 'Rp 2,329,500',
    picture: 'Galax GTX 1050 Ti OC Series Graphic Card [4GB DDR5].png',
  },
  {
    itemId: 19,
    name: 'Razer DeathAdder Chroma Gaming Mouse',
    casing: '-',
    category: 'mouse',
    brand: 'razer',
    price: 'Rp 1,010,000',
    picture: 'Razer DeathAdder Chroma Gaming Mouse.png',
  },
  {
    itemId: 20,
    name: 'ASUS Z170M Plus Motherboard',
    casing: 'all (mid-tower & tower)',
    category: 'motherboard',
    brand: 'asus',
    price: 'Rp 2,920,000',
    picture: 'ASUS Z170M Plus Motherboard.png',
  },
  {
    itemId: 21,
    name:
      'Cube Gaming Weiss Black Intel PC 1 [Intel Core i5-6400/GTX 1060 3GB/16GB RAM DDR4/120GB SSD/WIFI]',
    casing: '-',
    category: 'desktop PC',
    brand: 'cube',
    price: 'Rp 12,179,000',
    picture:
      'Cube Gaming Weiss Black Intel PC 1 [Intel Core i5-6400GTX 1060 3GB16GB RAM DDR4120GB SSDWIFI].png',
  },
  {
    itemId: 22,
    name: 'Galax nVidia Geforce GT 730 VGA Card [1 GB/DDR5/64 Bit]',
    casing: 'all (mid-tower & tower)',
    category: 'vga',
    brand: 'galax',
    price: 'Rp 955,000',
    picture: 'Galax nVidia Geforce GT 730 VGA Card [1 GBDDR564 Bit].png',
  },
  {
    itemId: 23,
    name: 'XFX Radeon R7 370 Black Edition VGA Card [2 GB/DDR5/Dual Fan]',
    casing: 'all (mid-tower & tower)',
    category: 'vga',
    brand: 'xfx',
    price: 'Rp 2,399,000',
    picture: 'XFX Radeon R7 370 Black Edition VGA Card [2 GBDDR5Dual Fan].png',
  },
  {
    itemId: 24,
    name: 'AMD Vishera FX-6300 Processor [3.5 Ghz/Cache 6MB/95W/AM3+/6 Core]',
    casing: 'all (mid-tower & tower)',
    category: 'prosesor',
    brand: 'amd',
    price: 'Rp 1,595,000',
    picture:
      'AMD Vishera FX-6300 Processor [3.5 GhzCache 6MB95WAM3+6 Core].png',
  },
  {
    itemId: 25,
    name:
      'AMD Godavari A8-7670K Prosesor [Radeon R7 series/3.6Ghz/Cache 2x2MB/95W/Socket FM2+]',
    casing: 'all (mid-tower & tower)',
    category: 'prosesor',
    brand: 'amd',
    price: 'Rp 1,835,000',
    picture:
      'AMD Godavari A8-7670K Prosesor [Radeon R7 series3.6GhzCache 2x2MB95WSocket FM2+].png',
  },
  {
    itemId: 26,
    name:
      'Antec NeoECO II Power Supply [550W/80+ Bronze Certified/3 Years Warranty]',
    casing: 'all (mid-tower & tower)',
    category: 'psu',
    brand: 'antec',
    price: 'Rp 1,049,000',
    picture:
      'Antec NeoECO II Power Supply [550W80+ Bronze Certified3 Years Warranty].png',
  },
  {
    itemId: 27,
    name:
      'AMD Kaveri Athlon X4-860K Prosesor [Quad Core 3.7Ghz/Cache 4MB/95W/Socket FM2+/With 95W Quiet Cooler]',
    casing: 'all (mid-tower & tower)',
    category: 'prosesor',
    brand: 'amd',
    price: 'Rp 1,299,000',
    picture:
      'AMD Kaveri Athlon X4-860K Prosesor [Quad Core 3.7GhzCache 4MB95WSocket FM2+With 95W Quiet Cooler].png',
  },
  {
    itemId: 28,
    name:
      'AMD Kaveri A8-7600 Prosesor [Radeon R7 series/3.1 Ghz/Cache 2x2MB/65W/Socket FM2+]',
    casing: 'all (mid-tower & tower)',
    category: 'proccesor',
    brand: 'amd',
    price: 'Rp 1,399,000',
    picture:
      'AMD Kaveri A8-7600 Prosesor [Radeon R7 series3.1 GhzCache 2x2MB65WSocket FM2+].png',
  },
  {
    itemId: 29,
    name:
      'Cube Gaming Weiss Black Intel PC 5 [Intel Core i7-6700K/GTX 1070 8GB/32GB RAM DDR4/240GB SSD/WIFI]',
    casing: '-',
    category: 'desktop PC',
    brand: 'cube',
    price: 'Rp 21,900,000',
    picture:
      'Cube Gaming Weiss Black Intel PC 5 [Intel Core i7-6700KGTX 1070 8GB32GB RAM DDR4240GB SSDWIFI].png',
  },
  {
    itemId: 30,
    name:
      'Gigabyte Geforce GV-N970IXOC-4GD VGA GTX970 OC Graphic card [4096MB/DDR5]',
    casing: 'all (mid-tower & tower)',
    category: 'vga',
    brand: 'gigabyte',
    price: 'Rp 7,100,000',
    picture:
      'Gigabyte Geforce GV-N970IXOC-4GD VGA GTX970 OC Graphic card [4096MBDDR5].png',
  },
  {
    itemId: 31,
    name: 'Sandisk Cruzer Ultra Fit CZ43 Flashdisk [USB 3.0/64 GB]',
    casing: '-',
    category: 'USB / flashdisk',
    brand: 'sandisk',
    price: 'Rp 287,000',
    picture: 'Sandisk Cruzer Ultra Fit CZ43 Flashdisk [USB 3.064 GB].png',
  },
  {
    itemId: 32,
    name: 'Samsung PRO 850 Hard Disk SSD [1 TB] + Kalender',
    casing: 'all (mid-tower & tower)',
    category: 'hard disk',
    brand: 'samsung',
    price: 'Rp 6,800,000',
    picture: 'Samsung PRO 850 Hard Disk SSD [1 TB] + Kalender.png',
  },
  {
    itemId: 33,
    name: 'Samsung 850 EVO SSD [2.5 Inch/250 GB]',
    casing: 'all (mid-tower & tower)',
    category: 'hard disk',
    brand: 'samsung',
    price: 'Rp 1,300,000',
    picture: 'Samsung 850 EVO SSD [2.5 Inch250 GB].png',
  },
  {
    itemId: 34,
    name: 'Galax nVidia Geforce GTX 950 EXOC VGA Card [2 GB/DDR5]',
    casing: 'all (mid-tower & tower)',
    category: 'vga',
    brand: 'galax',
    price: 'Rp 2,629,000',
    picture: 'Galax nVidia Geforce GTX 950 EXOC VGA Card [2 GBDDR5].png',
  },
  {
    itemId: 35,
    name:
      'Cube Gaming Weiss Black Intel PC 7 [Intel Core i7-6700K/GTX 1080 8GB/32GB RAM DDR4/240GB SSD/WIFI]',
    casing: '-',
    category: 'desktop PC',
    brand: 'cube',
    price: 'Rp 24,389,000',
    picture:
      'Cube Gaming Weiss Black Intel PC 7 [Intel Core i7-6700KGTX 1080 8GB32GB RAM DDR4240GB SSDWIFI].png',
  },
  {
    itemId: 36,
    name:
      'Galax nVidia Geforce GTX 960 EXOC VGA Card Black Edition [4 GB/DDR5]',
    casing: 'all (mid-tower & tower)',
    category: 'vga',
    brand: 'galax',
    price: 'Rp 4,215,000',
    picture:
      'Galax nVidia Geforce GTX 960 EXOC VGA Card – Black Edition [4 GBDDR5].png',
  },
  {
    itemId: 37,
    name: 'ASUS H81M-E Motherboard [Socket 1150]',
    casing: 'tower',
    category: 'motherboard',
    brand: 'asus',
    price: 'Rp 1,048,000',
    picture: 'ASUS H81M-E Motherboard [Socket 1150].png',
  },
  {
    itemId: 38,
    name: "Galax nVidia GTX1070 Founder's Edition VGA card",
    casing: 'all (mid-tower & tower)',
    category: 'vga',
    brand: 'galax',
    price: 'Rp 8,240,000',
    picture: "Galax nVidia GTX1070 Founder's Edition VGA card.png",
  },
  {
    itemId: 39,
    name: 'Cougar 700M eSpoprts Edition Aluminum Laser Gaming Mouse - White',
    casing: '-',
    category: 'mouse',
    brand: 'cougar',
    price: 'Rp 897,000',
    picture:
      'Cougar 700M eSpoprts Edition Aluminum Laser Gaming Mouse - White.png',
  },
  {
    itemId: 40,
    name:
      'Galax nVidia Geforce GTX 950 OC Mini Single Fan VGA Card [2 GB/DDR5]',
    casing: 'all (mid-tower & tower)',
    category: 'vga',
    brand: 'galax',
    price: 'Rp 2,495,000',
    picture:
      'Galax nVidia Geforce GTX 950 OC Mini Single Fan VGA Card [2 GBDDR5].png',
  },
  {
    itemId: 41,
    name: 'Asus H170 Plus D3 Motherboard [LGA 1151/H170/DDR3]',
    casing: 'all (mid-tower & tower)',
    category: 'motherboard',
    brand: 'asus',
    price: 'Rp 2,515,000',
    picture: 'Asus H170 Plus D3 Motherboard [LGA 1151H170DDR3].png',
  },
  {
    itemId: 42,
    name:
      'Acer Aspire intel Gen 7 E5-475G Notebook [Core I5 Gen7 Kabylake 7200U/NVidia Gforce GT940MX/Intel HD 620/DDR4]',
    casing: '-',
    category: 'laptop',
    brand: 'acer',
    price: 'Rp 7,299,999',
    picture:
      'Acer Aspire intel Gen 7 E5-475G Notebook [Core I5 Gen7 Kabylake 7200UNVidia Gforce GT940MXIntel HD 620DDR4].png',
  },
  {
    itemId: 43,
    name: 'Kingston DTDUO3 Flashdisk OTG [16 GB/USB 3.0]',
    casing: '-',
    category: 'USB / flashdisk',
    brand: 'kingston',
    price: 'Rp 149,800',
    picture: 'Kingston DTDUO3 Flashdisk OTG [16 GBUSB 3.0].png',
  },
  {
    itemId: 44,
    name: 'Galax Gamer SSD Hard Disk [120 GB]',
    casing: 'all (mid-tower & tower)',
    category: 'hard disk',
    brand: 'galax',
    price: 'Rp 750,000',
    picture: 'Galax Gamer SSD Hard Disk [120 GB].png',
  },
  {
    itemId: 45,
    name: 'Galax GAMER SSD [480 GB]',
    casing: 'all (mid-tower & tower)',
    category: 'hard disk',
    brand: 'galax',
    price: 'Rp 2,092,000',
    picture: 'Galax GAMER SSD [480 GB].png',
  },
  {
    itemId: 46,
    name: 'Crucial MX200 Hard Disk [500 GB]',
    casing: 'all (mid-tower & tower)',
    category: 'hard disk',
    brand: 'crucial',
    price: 'Rp 2,749,900',
    picture: 'Crucial MX200 Hard Disk [500 GB].png',
  },
  {
    itemId: 47,
    name: 'Galax nVidia Geforce GTX 980 Ti VGA Card - Black Edition [6GB/DDR5]',
    casing: 'all (mid-tower & tower)',
    category: 'vga',
    brand: 'galax',
    price: 'Rp 10,900,000',
    picture:
      'Galax nVidia Geforce GTX 980 Ti VGA Card - Black Edition [6GBDDR5].png',
  },
  {
    itemId: 48,
    name:
      'AMD Vishera FX-8320E Prosesor [3.2 Ghz/Cache 8 MB/95 watt/AM3+/8 Core]',
    casing: 'all (mid-tower & tower)',
    category: 'prosesor',
    brand: 'amd',
    price: 'Rp 2,125,000',
    picture:
      'AMD Vishera FX-8320E Prosesor [3.2 GhzCache 8 MB95 wattAM3+8 Core].png',
  },
  {
    itemId: 49,
    name:
      'Raijintek Nestor 5 Desktop PC - Black [Intel i5-6500 Skylake/Radeon RX 470 4GB/16GB RAM/SSD 240GB/WIFI/Win 10]',
    casing: '-',
    category: 'desktop',
    brand: 'raijintek',
    price: 'Rp 16,230,000',
    picture:
      'Raijintek Nestor 5 Desktop PC - Black [Intel i5-6500 SkylakeRadeon RX 470 4GB16GB RAMSSD 240GBWIFIWin 10].png',
  },
  {
    itemId: 50,
    name:
      'Raijintek Nestor 6 PC Desktop - Black [Intel i5-6500 Skylake/Nvidia GTX 1060 6GB/16 GB RAM/SSD 240 GB/WIFI/Win 10]',
    casing: '-',
    category: 'desktop',
    brand: 'raijintek',
    price: 'Rp 17,770,000',
    picture:
      'Raijintek Nestor 6 PC Desktop - Black [Intel i5-6500 SkylakeNvidia GTX 1060 6GB16 GB RAMSSD 240 GBWIFIWin 10].png',
  },
  {
    itemId: 51,
    name: 'Asus X556UQ-XX040T [i5 6200/8GB/Nvidia GT940MX-2GB/15.6 inch]',
    casing: '-',
    category: 'laptop',
    brand: 'asus',
    price: 'Rp 9,299,000',
    picture: 'Asus X556UQ-XX040T [i5 62008GBNvidia GT940MX-2GB15.6 inch].png',
  },
  {
    itemId: 52,
    name:
      'Acer Aspire E5-475G Notebook [14 inch/i3-6100U/nVidia GT940MX/2 GB/500 GB]',
    casing: '-',
    category: 'laptop',
    brand: 'acer',
    price: 'Rp 6,099,000',
    picture:
      'Acer Aspire E5-475G Notebook [14 inchi3-6100UnVidia GT940MX2 GB500 GB].png',
  },
  {
    itemId: 53,
    name:
      'Antec NeoECO II Power Supply [450W/80+ Bronze Certified/3 Years Warranty]',
    casing: 'all (mid-tower & tower)',
    category: 'PSU',
    brand: 'antec',
    price: 'Rp 885,000',
    picture:
      'Antec NeoECO II Power Supply [450W80+ Bronze Certified3 Years Warranty].png',
  },
  {
    itemId: 54,
    name: 'Galax nVidia Geforce GT 740 OC Slim VGA Card [2 GB/DDR5]',
    casing: 'all (mid-tower & tower)',
    category: 'vga',
    brand: 'galax',
    price: 'Rp 1,685,000',
    picture: 'Galax nVidia Geforce GT 740 OC Slim VGA Card [2 GBDDR5].png',
  },
  {
    itemId: 55,
    name: 'Kingston DataTraveler Generation 4 DTIG4 Flashdisk [16 GB]',
    casing: '-',
    category: 'USB / flashdisk',
    brand: 'kingston',
    price: 'Rp 130,000',
    picture: 'Kingston DataTraveler Generation 4 DTIG4 Flashdisk [16 GB].png',
  },
  {
    itemId: 56,
    name: 'Samsung 850 PRO Hard Disk SSD [128 GB/2.5 Inch]',
    casing: '-',
    category: 'hard disk',
    brand: 'samsung',
    price: 'Rp 1,300,000',
    picture: 'Samsung 850 PRO Hard Disk SSD [128 GB2.5 Inch].png',
  },
  {
    itemId: 57,
    name: 'Cougar 550M Gaming Mouse - Blue',
    casing: '-',
    category: 'mouse',
    brand: 'cougar',
    price: 'Rp 679,000',
    picture: 'Cougar 550M Gaming Mouse - Blue.png',
  },
  {
    itemId: 58,
    name: 'Galax nVidia Geforce GTX 1060 EXOC Dual Fan [6GB/DDR5]',
    casing: 'all (mid-tower & tower)',
    category: 'vga',
    brand: 'galax',
    price: 'Rp 4,459,000',
    picture: 'Galax nVidia Geforce GTX 1060 EXOC Dual Fan [6GBDDR5].png',
  },
  {
    itemId: 59,
    name:
      'iGame nVidia Geforce GTX 1080 X-TOP-8G Graphic Card [8GB DDR5X/Triple Fan]',
    casing: 'all (mid-tower & tower)',
    category: 'vga',
    brand: 'Igame',
    price: 'Rp 9,959,000',
    picture:
      'iGame nVidia Geforce GTX 1080 X-TOP-8G Graphic Card [8GB DDR5XTriple Fan].png',
  },
  {
    itemId: 60,
    name:
      'Cube Gaming Weiss Black Intel PC 2 [Intel Core i5-6500/GTX 1060 6GB/16GB RAM DDR4/240GB SSD/WIFI]',
    casing: '-',
    category: 'desktop PC',
    brand: 'cube',
    price: 'Rp 17,030,000',
    picture:
      'Cube Gaming Weiss Black Intel PC 2 [Intel Core i5-6500GTX 1060 6GB16GB RAM DDR4240GB SSDWIFI].png',
  },
  {
    itemId: 61,
    name: 'Segotep S2 Intel PC [intel G3250 /4GB RAM/320GB HDD/WIFI]',
    casing: '-',
    category: 'desktop PC',
    brand: 'segotep',
    price: 'Rp 2,989,000',
    picture: 'Segotep S2 Intel PC [intel G3250 4GB RAM320GB HDDWIFI].jpg',
  },
  {
    itemId: 62,
    name:
      'ACER Aspire E5-475G Win 10 Notebook [i5-6200U/]4GB DDR4/GT 940M 2GB/SSD 128GB',
    casing: '-',
    category: 'laptop',
    brand: 'acer',
    price: 'Rp 8,999,999',
    picture:
      'ACER Aspire E5-475G Win 10 Notebook [i5-6200U]4GB DDR4GT 940M 2GBSSD 128GB.png',
  },
  {
    itemId: 63,
    name:
      'Galax nVidia Geforce GTX 980 Ti HOF VGA Card - GOC Edition [6GB/DDR5]',
    casing: 'all (mid-tower & tower)',
    category: 'vga',
    brand: 'galax',
    price: 'Rp 11,350,000',
    picture:
      'Galax nVidia Geforce GTX 980 Ti HOF VGA Card - GOC Edition [6GBDDR5].png',
  },
  {
    itemId: 64,
    name: 'Galax nVidia Geforce GT 730 VGA Card [2 GB/DDR3/128 Bit]',
    casing: 'all (mid-tower & tower)',
    category: 'vga',
    brand: 'galax',
    price: 'Rp 995,800',
    picture: 'Galax nVidia Geforce GT 730 VGA Card [2 GBDDR3128 Bit].png',
  },
  {
    itemId: 65,
    name: 'Galax GeForce GTX 1080 EXOC Graphic Card [8GB DDR5X/Dual Fan]',
    casing: 'all (mid-tower & tower)',
    category: 'vga',
    brand: 'galax',
    price: 'Rp 14,955,000',
    picture: 'Galax GeForce GTX 1080 EXOC Graphic Card [8GB DDR5XDual Fan].png',
  },
  {
    itemId: 66,
    name: 'Cougar 700K Cherry MX Brown switch Mechanical Gaming Keyboard',
    casing: '-',
    category: 'keyboard',
    brand: 'cougar',
    price: 'Rp 1,915,000',
    picture:
      'Cougar 700K Cherry MX Brown switch Mechanical Gaming Keyboard.png',
  },
  {
    itemId: 67,
    name: 'Cougar 450M Gaming Mouse - Black',
    casing: '-',
    category: 'mouse',
    brand: 'cougar',
    price: 'Rp 628,000',
    picture: 'Cougar 450M Gaming Mouse - Black.png',
  },
  {
    itemId: 68,
    name:
      'Antec Edge EDG650 Power Supply [650 W/80+ Gold Certified/Full Modular/LED Fan/5 Years Warranty]',
    casing: 'all (mid-tower & tower)',
    category: 'psu',
    brand: 'antec',
    price: 'Rp 1,865,000',
    picture:
      'Antec Edge EDG650 Power Supply [650 W80+ Gold CertifiedFull ModularLED Fan5 Years Warranty].png',
  },
  {
    itemId: 69,
    name:
      'Asus X456UQ-WX016T Metal Notebook [14Inch/i5-6200U/Nvidia GT940MX 2GB/8GB/1TB]',
    casing: '-',
    category: 'laptop',
    brand: 'asus',
    price: 'Rp 9,099,000',
    picture:
      'Asus X456UQ-WX016T Metal Notebook [14Inchi5-6200UNvidia GT940MX 2GB8GB1TB].png',
  },
  {
    itemId: 70,
    name: 'Galax nVidia Geforce GTX 980 HOF VGA Card [4GB/DDR5]',
    casing: 'all (mid-tower & tower)',
    category: 'vga',
    brand: 'galax',
    price: 'Rp 8,650,000',
    picture: 'Galax nVidia Geforce GTX 980 HOF VGA Card [4GBDDR5].png',
  },
  {
    itemId: 71,
    name: 'Galax nVidia Geforce GTX 1070 EXOC Dual Fan [8 GB DDR5]',
    casing: 'all (mid-tower & tower)',
    category: 'vga',
    brand: 'galax',
    price: 'Rp 7,370,000',
    picture: 'Galax nVidia Geforce GTX 1070 EXOC Dual Fan [8 GB DDR5].png',
  },
  {
    itemId: 72,
    name:
      'Igame nVidia Geforce GTX 1070 Graphic Card [8GB DDR5/U-TOP-8G/Triple Fan]',
    casing: 'all (mid-tower & tower)',
    category: 'vga',
    brand: 'Igame',
    price: 'Rp 6,399,000',
    picture:
      'Igame nVidia Geforce GTX 1070 Graphic Card [8GB DDR5U-TOP-8GTriple Fan].png',
  },
  {
    itemId: 73,
    name: 'Sandisk Cruzer Ultra Fit CZ43 Flashdisk [USB 3.0/32 GB]',
    casing: '-',
    category: 'USB / flashdisk',
    brand: 'sandisk',
    price: 'Rp 161,000',
    picture: 'Sandisk Cruzer Ultra Fit CZ43 Flashdisk [USB 3.032 GB].png',
  },
  {
    itemId: 74,
    name: 'Sandisk CZ73 Ultra Flair Flashdisk [16 GB/USB 3.0/130 MB/s]',
    casing: '-',
    category: 'USB / flashdisk',
    brand: 'sandisk',
    price: 'Rp 123,000',
    picture: 'Sandisk CZ73 Ultra Flair Flashdisk [16 GBUSB 3.0130 MBs].png',
  },
  {
    itemId: 75,
    name:
      'Cougar Attack X3 Mechanical Gaming Keyboard - Cherry MX Brown switch',
    casing: '-',
    category: 'keyboard',
    brand: 'cougar',
    price: 'Rp 1,535,000',
    picture:
      'Cougar Attack X3 Mechanical Gaming Keyboard - Cherry MX Brown switch.png',
  },
  {
    itemId: 76,
    name: 'Cougar 500K Membrane Gaming Keyboard',
    casing: '-',
    category: 'keyboard',
    brand: 'cougar',
    price: 'Rp 1,039,000',
    picture: 'Cougar 500K Membrane Gaming Keyboard.png',
  },
  {
    itemId: 77,
    name: 'Cougar Attack X3 Mechanical Gaming Keyboard - Cherry MX Blue switch',
    casing: '-',
    category: 'keyboard',
    brand: 'cougar',
    price: 'Rp 1,535,000',
    picture:
      'Cougar Attack X3 Mechanical Gaming Keyboard - Cherry MX Blue switch.png',
  },
  {
    itemId: 78,
    name: 'Samsung 850 EVO 120 GB Hard Disk SSD + Kalender',
    casing: 'all (mid-tower & tower)',
    category: 'hard disk',
    brand: 'samsung',
    price: 'Rp 893,500',
    picture: 'Samsung 850 EVO 120 GB Hard Disk SSD + Kalender.png',
  },
  {
    itemId: 79,
    name: 'Crucial BX200 Hard Disk [960 GB]',
    casing: 'all (mid-tower & tower)',
    category: 'hard disk',
    brand: 'crucial',
    price: 'Rp 4,450,000',
    picture: 'Crucial BX200 Hard Disk [960 GB].png',
  },
  {
    itemId: 80,
    name: 'Crucial MX200 Hard Disk [250 GB]',
    casing: 'all (mid-tower & tower)',
    category: 'hard disk',
    brand: 'crucial',
    price: 'Rp 1,485,000',
    picture: 'Crucial MX200 Hard Disk [250 GB].png',
  },
  {
    itemId: 81,
    name: 'Razer Naga 2014 Gaming Mouse',
    casing: '-',
    category: 'mouse',
    brand: 'razer',
    price: 'Rp 950,000',
    picture: 'Razer Naga 2014 Gaming Mouse.png',
  },
  {
    itemId: 82,
    name: 'Zotac nVidia Geforce GTX 1060 Mini Edition Graphic Card [6GB DDR5]',
    casing: 'all (mid-tower & tower)',
    category: 'vga',
    brand: 'zotac',
    price: 'Rp 5,090,000',
    picture:
      'Zotac nVidia Geforce GTX 1060 Mini Edition Graphic Card [6GB DDR5].png',
  },
  {
    itemId: 83,
    name:
      'iGame nVidia Geforce GTX 1080 U-TOP-8G Graphic Card [8GB DDR5X/Triple Fan]',
    casing: 'all (mid-tower & tower)',
    category: 'vga',
    brand: 'Igame',
    price: 'Rp 9,659,000',
    picture:
      'iGame nVidia Geforce GTX 1080 U-TOP-8G Graphic Card [8GB DDR5XTriple Fan].png',
  },
  {
    itemId: 84,
    name:
      'Raijintek Nestor 5 Desktop PC - Black [Intel i5-6500 Skylake/Radeon RX 470 4GB/16GB RAM/SSD 240GB/WIFI/Win 10/22 Inch LED FHD/Keyboard/Mouse]',
    casing: '-',
    category: 'desktop',
    brand: 'raijintek',
    price: 'Rp 19,990,000',
    picture:
      'Raijintek Nestor 5 Desktop PC - Black [Intel i5-6500 SkylakeRadeon RX 470 4GB16GB RAMSSD 240GBWIFIWin 1022 Inch LED FHDKeyboardMouse].png',
  },
  {
    itemId: 85,
    name:
      'Antec Edge EDG750 Power Supply [750 W/80+ Gold Certified/Full Modular/LED Fan/5 Years Warranty]',
    casing: 'all (mid-tower & tower)',
    category: 'psu',
    brand: 'antec',
    price: 'Rp 2,085,000',
    picture:
      'Antec Edge EDG750 Power Supply [750 W80+ Gold CertifiedFull ModularLED Fan5 Years Warranty].png',
  },
  {
    itemId: 86,
    name: 'Avexir SO-DIMM DDR3 PC12800 Memory RAM [8 GB/1 x 8/Low Voltage]',
    casing: 'all (mid-tower & tower)',
    category: 'ram',
    brand: 'avexir',
    price: 'Rp 562,000',
    picture:
      'Avexir SO-DIMM DDR3 PC12800 Memory RAM [8 GB1 x 8Low Voltage].png',
  },
  {
    itemId: 87,
    name: 'ASRock H110M-HDV Motherboard [LGA 1151/H110/DDR4]',
    casing: 'tower',
    category: 'motherboard',
    brand: 'asrock',
    price: 'Rp 1,298,000',
    picture: 'ASRock H110M-HDV Motherboard [LGA 1151H110DDR4].png',
  },
  {
    itemId: 88,
    name: 'Galax Gamer SSD Hard Disk [240 GB]',
    casing: 'all (mid-tower & tower)',
    category: 'hard disk',
    brand: 'galax',
    price: 'Rp 1,250,000',
    picture: 'Galax Gamer SSD Hard Disk [240 GB].png',
  },
  {
    itemId: 89,
    name: 'Crucial BX200 Hard Disk [480 GB]',
    casing: 'all (mid-tower & tower)',
    category: 'hard disk',
    brand: 'galax',
    price: 'Rp 1,250,000',
    picture: 'Crucial BX200 Hard Disk [480 GB].png',
  },
  {
    itemId: 90,
    name: 'Cougar SPEED-S Gaming Mouse Pad [260 x 210 x 4mm]',
    casing: 'all (mid-tower & tower)',
    category: 'hard disk',
    brand: 'cougar',
    price: 'Rp 145,000',
    picture: 'Cougar SPEED-S Gaming Mouse Pad [260 x 210 x 4mm].png',
  },
  {
    itemId: 91,
    name: 'Cougar 530M Gaming Mouse - Silver',
    casing: '-',
    category: 'mouse',
    brand: 'cougar',
    price: 'Rp 629,000',
    picture: 'Cougar 530M Gaming Mouse - Silver.png',
  },
  {
    itemId: 92,
    name: 'Cougar 500M Gaming Mouse - Black',
    casing: '-',
    category: 'mouse',
    brand: 'cougar',
    price: 'Rp 508,000',
    picture: 'Cougar 500M Gaming Mouse - Black.png',
  },
  {
    itemId: 93,
    name:
      'Antec NeoECO II Power Supply [650W/80+ Bronze Certified/3 Years Warranty]',
    casing: 'all (mid-tower & tower)',
    category: 'psu',
    brand: 'antec',
    price: 'Rp 1,249,000',
    picture:
      'Antec NeoECO II Power Supply [650W80+ Bronze Certified3 Years Warranty].png',
  },
  {
    itemId: 94,
    name: 'Antec Kuhler H2O H1200 PRO CPU Cooler [240mm Radiator/Dual Fan]',
    casing: 'all (mid-tower & tower)',
    category: 'cpu cooler',
    brand: 'antec',
    price: 'Rp 1,499,000',
    picture:
      'Antec Kuhler H2O H1200 PRO CPU Cooler [240mm RadiatorDual Fan].png',
  },
  {
    itemId: 95,
    name:
      'Galax nVidia Geforce GTX 1070 HOF Graphic Card [8GB DDR5/Triple Fan]',
    casing: 'all (mid-tower & tower)',
    category: 'vga',
    brand: 'galax',
    price: 'Rp Rp 7,990,000',
    picture:
      'Galax nVidia Geforce GTX 1070 HOF Graphic Card [8GB DDR5Triple Fan].png',
  },
  {
    itemId: 96,
    name: 'ASUS H170 Pro Gaming Skylake Motherboard',
    casing: 'all (mid-tower & tower)',
    category: 'motherboard',
    brand: 'asus',
    price: 'Rp 2,810,000',
    picture: 'ASUS H170 Pro Gaming Skylake Motherboard.png',
  },
  {
    itemId: 97,
    name: 'Antec High Current Pro PC Power Supply',
    casing: 'all (mid-tower & tower)',
    category: 'psu',
    brand: 'antec',
    price: 'Rp 4,390,000',
    picture: 'Antec High Current Pro PC Power Supply.png',
  },
  {
    itemId: 98,
    name: 'ASUS H170 Pro Gaming Skylake Motherboard',
    casing: 'all (mid-tower & tower)',
    category: 'motherboard',
    brand: 'asus',
    price: 'Rp 2,810,000',
    picture: 'ASUS H170 Pro Gaming Skylake Motherboard.png',
  },
  {
    itemId: 99,
    name:
      'Antec Edge EDG550 Power Supply [550 W/80+ Gold Certified/Full Modular/LED Fan/5 Years Warranty]',
    casing: 'all (mid-tower & tower)',
    category: 'psu',
    brand: 'antec',
    price: 'Rp 1,670,000',
    picture:
      'Antec Edge EDG550 Power Supply [550 W80+ Gold CertifiedFull ModularLED Fan5 Years Warranty].png',
  },
  {
    itemId: 100,
    name: 'Antec High Current Pro PC Power Supply',
    casing: 'all (mid-tower & tower)',
    category: 'psu',
    brand: 'antec',
    price: 'Rp 4,480,000',
    picture: 'Antec High Current Pro PC Power Supply.png',
  },
  {
    itemId: 101,
    name:
      'Gigabyte GA-Z170-HD3 Intel Z170 Motherboard [LGA1151/DDR4/USB3.1/ATX]',
    casing: 'tower',
    category: 'motherboard',
    brand: 'gigabyte',
    price: 'Rp 2,990,000',
    picture:
      'Gigabyte GA-Z170-HD3 Intel Z170 Motherboard [LGA1151DDR4USB3.1ATX].png',
  },
  {
    itemId: 102,
    name: 'MSI H110M-PRO VH Motherboard [LGA 1151/H110/DDR4]',
    casing: 'all (mid-tower & tower)',
    category: 'motherboard',
    brand: 'msi',
    price: 'Rp 1,429,000',
    picture: 'MSI H110M-PRO VH Motherboard [LGA 1151H110DDR4].png',
  },
  {
    itemId: 103,
    name: 'MSi B150M-PRO VDH Motherboard [LGA 1151/B150/DDR4]',
    casing: 'tower',
    category: 'motherboard',
    brand: 'msi',
    price: 'Rp 1,798,000',
    picture: 'MSi B150M-PRO VDH Motherboard [LGA 1151B150DDR4].png',
  },
  {
    itemId: 104,
    name:
      'Igame nVidia Geforce GTX 1070 Graphic Card [8GB DDR5/X-TOP-8G/Triple Fan]',
    casing: 'all (mid-tower & tower)',
    category: 'vga',
    brand: 'Igame',
    price: 'Rp 6,779,000',
    picture:
      'Igame nVidia Geforce GTX 1070 Graphic Card [8GB DDR5X-TOP-8GTriple Fan].png',
  },
  {
    itemId: 105,
    name:
      'Segotep AND 2 TT Desktop PC [Intel PC Bundle-G4400 Skylake/4GB RAM DDR4] + Free Wifi USB Adapter',
    casing: '-',
    category: 'desktop PC',
    brand: 'segotep',
    price: 'Rp 3,520,000',
    picture:
      'Segotep AND 2 TT Desktop PC [Intel PC Bundle-G4400 Skylake4GB RAM DDR4] + Free Wifi USB Adapter.png',
  },
  {
    itemId: 106,
    name:
      'Segotep AND 1 Desktop PC [Intel PC Bundle/G4400 Skylake/4GB RAM DDR4]',
    casing: '-',
    category: 'desktop PC',
    brand: 'segotep',
    price: 'Rp 3,399,000',
    picture:
      'Segotep AND 1 Desktop PC [Intel PC BundleG4400 Skylake4GB RAM DDR4].png',
  },
  {
    itemId: 107,
    name: 'Sandisk Cruzer Fit CZ33 Flashdisk [8 GB]',
    casing: '-',
    category: 'USB / flashdisk',
    brand: 'sandisk',
    price: 'Rp 73,000',
    picture: 'Sandisk Cruzer Fit CZ33 Flashdisk [8 GB].png',
  },
  {
    itemId: 108,
    name: 'Sandisk Cruzer Ultra Fit CZ43 Flashdisk [USB 3.0/16 GB]',
    casing: '-',
    category: 'USB / flashdisk',
    brand: 'sandisk',
    price: 'Rp 139,000',
    picture: 'Sandisk Cruzer Ultra Fit CZ43 Flashdisk [USB 3.016 GB].png',
  },
  {
    itemId: 109,
    name: 'Sandisk Ultra CZ48 USB 3.0 Flashdisk [64 GB]',
    casing: '-',
    category: 'USB / flashdisk',
    brand: 'sandisk',
    price: 'Rp 265,000',
    picture: 'Sandisk Ultra CZ48 USB 3.0 Flashdisk [64 GB].png',
  },
  {
    itemId: 110,
    name: 'SteelSeries Rival 300 Black Gaming Mouse',
    casing: '-',
    category: 'mouse',
    brand: 'steelseries',
    price: 'Rp 950,000',
    picture: 'SteelSeries Rival 300 Black Gaming Mouse.png',
  },
  {
    itemId: 111,
    name: 'Cougar 300M Gaming Mouse - Orange',
    casing: '-',
    category: 'mouse',
    brand: 'cougar',
    price: 'Rp 508,000',
    picture: 'Cougar 300M Gaming Mouse - Orange.png',
  },
  {
    itemId: 112,
    name: 'Cougar Cougar 250M Gaming Mouse - White',
    casing: '-',
    category: 'mouse',
    brand: 'cougar',
    price: 'Rp 399,700',
    picture: 'Cougar Cougar 250M Gaming Mouse - White.png',
  },
  {
    itemId: 113,
    name: 'Cougar 230M Gaming Mouse - Yellow',
    casing: '-',
    category: 'mouse',
    brand: 'cougar',
    price: 'Rp 293,000',
    picture: 'Cougar 230M Gaming Mouse - Yellow.png',
  },
  {
    itemId: 114,
    name: 'Cougar CONTROL-L Gaming Mouse Pad [450 x 400 x 4mm]',
    casing: '-',
    category: 'mouse pad',
    brand: 'cougar',
    price: 'Rp 223,000',
    picture: 'Cougar CONTROL-L Gaming Mouse Pad [450 x 400 x 4mm].png',
  },
  {
    itemId: 115,
    name: 'Cougar 700M eSpoprts Edition Aluminum Laser Gaming Mouse - Black',
    casing: '-',
    category: 'mouse',
    brand: 'cougar',
    price: 'Rp 897,000',
    picture:
      'Cougar 700M eSpoprts Edition Aluminum Laser Gaming Mouse - Black.png',
  },
  {
    itemId: 116,
    name: 'Cougar 550M Gaming Mouse - Iron Grey',
    casing: '-',
    category: 'mouse',
    brand: 'cougar',
    price: 'Rp 679,000',
    picture: 'Cougar 550M Gaming Mouse - Iron Grey.png',
  },
  {
    itemId: 117,
    name: 'Cougar 530M Gaming Mouse - Army Green',
    casing: '-',
    category: 'mouse',
    brand: 'cougar',
    price: 'Rp 629,000',
    picture: 'Cougar 530M Gaming Mouse - Army Green.png',
  },
  {
    itemId: 118,
    name: 'Cougar 500M Gaming Mouse - White',
    casing: '-',
    category: 'mouse',
    brand: 'cougar',
    price: 'Rp 508,000',
    picture: 'Cougar 500M Gaming Mouse - White.png',
  },
  {
    itemId: 119,
    name: 'Cougar 400M Gaming Mouse - Grey',
    casing: '-',
    category: 'mouse',
    brand: 'cougar',
    price: 'Rp 525,000',
    picture: 'Cougar 400M Gaming Mouse - Grey.png',
  },
  {
    itemId: 120,
    name: 'Cougar 300M Gaming Mouse - Yellow',
    casing: '-',
    category: 'mouse',
    brand: 'cougar',
    price: 'Rp 508,000',
    picture: 'Cougar 300M Gaming Mouse - Yellow.png',
  },
  {
    itemId: 121,
    name: 'Cougar 230M Gaming Mouse - Red',
    casing: '-',
    category: 'mouse',
    brand: 'cougar',
    price: 'Rp 293,000',
    picture: 'Cougar 230M Gaming Mouse - Red.png',
  },
  {
    itemId: 122,
    name: 'Cougar 200M Gaming Mouse - Orange',
    casing: '-',
    category: 'mouse',
    brand: 'cougar',
    price: 'Rp 239,000',
    picture: 'Cougar 200M Gaming Mouse - Orange.png',
  },
  {
    itemId: 123,
    name: 'SteelSeries Sensei COD Ops 2 Mouse - Black',
    casing: '-',
    category: 'mouse',
    brand: 'steelseries',
    price: 'Rp 885,000',
    picture: 'SteelSeries Sensei COD Ops 2 Mouse - Black.png',
  },
  {
    itemId: 124,
    name: 'Cougar 700K Cherry MX switch Mechanical Gaming Keyboard - Blue',
    casing: '-',
    category: 'keyboard',
    brand: 'cougar',
    price: 'Rp 1,915,000',
    picture:
      'Cougar 700K Cherry MX switch Mechanical Gaming Keyboard - Blue.png',
  },
  {
    itemId: 125,
    name: 'Cougar 600K Cherry MX Red switch Mechanical Gaming Keyboard',
    casing: '-',
    category: 'keyboard',
    brand: 'cougar',
    price: 'Rp 1,589,000',
    picture: 'Cougar 600K Cherry MX Red switch Mechanical Gaming Keyboard.png',
  },
  {
    itemId: 126,
    name: 'SteelSeries Rival 300 Black Gaming Mouse',
    casing: '-',
    category: 'mouse',
    brand: 'steelseries',
    price: 'Rp 950,000',
    picture: 'SteelSeries Rival 300 Black Gaming Mouse.png',
  },
  {
    itemId: 127,
    name: 'Cougar 200M Gaming Mouse - Black',
    casing: '-',
    category: 'mouse',
    brand: 'cougar',
    price: 'Rp 239,000',
    picture: 'Cougar 200M Gaming Mouse - Black.png',
  },
  {
    itemId: 128,
    name: 'Cougar CONTROL-M Gaming Mouse Pad [320 x 270 x 4mm]',
    casing: '-',
    category: 'mouse pad',
    brand: 'cougar',
    price: 'Rp 178,000',
    picture: 'Cougar CONTROL-M Gaming Mouse Pad [320 x 270 x 4mm].png',
  },
  {
    itemId: 129,
    name: 'Cougar SPEED-M Gaming Mouse Pad [320 x 270 x 4mm]',
    casing: '-',
    category: 'mouse pad',
    brand: 'cougar',
    price: 'Rp 178,000',
    picture: 'Cougar SPEED-M Gaming Mouse Pad [320 x 270 x 4mm].png',
  },
  {
    itemId: 130,
    name:
      'MSI GE62VR 6RF Apache Pro [Intel i7-6700HQ/GTX 1060 6GB/RAM 16GB/128GB SSD]',
    casing: '-',
    category: 'laptop',
    brand: 'msi',
    price: 'Rp 25,999,000',
    picture:
      'MSI GE62VR 6RF Apache Pro [Intel i7-6700HQGTX 1060 6GBRAM 16GB128GB SSD].png',
  },
  {
    itemId: 131,
    name:
      'Avexir DDR3 PC12800 Memory RAM for PC - Core Blue [8 GB/2 x 4 GB/KIT Dual Channel]',
    casing: 'all (mid-tower & tower)',
    category: 'ram',
    brand: 'avexir',
    price: 'Rp 690,000',
    picture:
      'Avexir DDR3 PC12800 Memory RAM for PC - Core Blue [8 GB2 x 4 GBKIT Dual Channel].png',
  },
  {
    itemId: 132,
    name: 'Linksys E1200 Hitam Wireless N Router',
    casing: '-',
    category: 'router',
    brand: 'linksys',
    price: 'Rp 498,900',
    picture: 'Linksys E1200 Hitam Wireless N Router.png',
  },
  {
    itemId: 133,
    name: 'Steel Series Rival 100 Dota 2 Edition Gaming Mouse',
    casing: '-',
    category: 'router',
    brand: 'steelseries',
    price: 'Rp 925,000',
    picture: 'Steel Series Rival 100 Dota 2 Edition Gaming Mouse.png',
  },
  {
    itemId: 134,
    name: 'Kingfast SSD F6 [30GB]',
    casing: 'all (mid-tower & tower)',
    category: 'ssd',
    brand: 'kingfast',
    price: 'Rp 390,000',
    picture: 'Kingfast SSD F6 [30GB].png',
  },
  {
    itemId: 135,
    name: 'Kingfast SSD F6 [120 GB]',
    casing: 'all (mid-tower & tower)',
    category: 'ssd',
    brand: 'kingfast',
    price: 'Rp 859,000',
    picture: 'Kingfast SSD F6 [120 GB].png',
  },
  {
    itemId: 136,
    name: 'Crucial BX200 Hard Disk [240 GB]',
    casing: 'all (mid-tower & tower)',
    category: 'ssd',
    brand: 'crucial',
    price: 'Rp 1,162,000',
    picture: 'Crucial BX200 Hard Disk [240 GB].png',
  },
  {
    itemId: 137,
    name: 'Crucial MX200 Hard Disk [1 TB]',
    casing: 'all (mid-tower & tower)',
    category: 'ssd',
    brand: 'crucial',
    price: 'Rp 5,467,000',
    picture: 'Crucial MX200 Hard Disk [1 TB].png',
  },
  {
    itemId: 138,
    name:
      'Antec High Current Pro PC Power Supply [850 W/80+ Platinum Certified/Full Modular/7 Years Warranty]',
    casing: 'all (mid-tower & tower)',
    category: 'psu',
    brand: 'antec',
    price: 'Rp 3,399,000',
    picture:
      'Antec High Current Pro PC Power Supply [850 W80+ Platinum CertifiedFull Modular7 Years Warranty].png',
  },
  {
    itemId: 139,
    name:
      'Raijintek Nestor Desktop PC - Black [Intel i7-6700K Skylake/Nvidia GTX 1060 6GB/16GB RAM/SSD 480GB/WiFi/Win 10]',
    casing: '-',
    category: 'desktop PC',
    brand: 'raijintek',
    price: 'Rp 21,185,000',
    picture:
      'Raijintek Nestor Desktop PC - Black [Intel i7-6700K SkylakeNvidia GTX 1060 6GB16GB RAMSSD 480GBWiFiWin 10].png',
  },
  {
    itemId: 140,
    name: 'Cougar QBX Gaming Mini ITX Case',
    casing: 'all (mid-tower & tower)',
    category: 'casing',
    brand: 'cougar',
    price: 'Rp 671,000',
    picture: 'Cougar QBX Gaming Mini ITX Case.png',
  },
  {
    itemId: 141,
    name: 'AMD Ryzen 5 1400',
    casing: 'all (mid-tower & tower)',
    category: 'proccesor',
    brand: 'amd',
    price: 'Rp 2,050,000',
    picture: 'AMD Ryzen 5 1400.png',
  },
  {
    itemId: 142,
    name: 'ASRock AB350M',
    casing: 'all (mid-tower & tower)',
    category: 'motherboard',
    brand: 'asrock',
    price: 'Rp 2,069,000',
    picture: 'ASRock AB350M.png',
  },
  {
    itemId: 143,
    name: 'Patriot Signature Line Kit Series 8GB (2 x 4GB) DDR4-2666',
    casing: 'all (mid-tower & tower)',
    category: 'RAM',
    brand: 'patriot',
    price: 'Rp 776,000',
    picture: 'Patriot Signature Line Kit Series 8GB (2 x 4GB) DDR4-2666.png',
  },
  {
    itemId: 144,
    name: 'Zotac GeForce GTX 1050 2GB DDR5',
    casing: 'all (mid-tower & tower)',
    category: 'VGA',
    brand: 'zotac',
    price: 'Rp 1,880,000',
    picture: 'Zotac GeForce GTX 1050 2GB DDR5.png',
  },
  {
    itemId: 145,
    name: 'Antec VP Series 500W',
    casing: 'all (mid-tower & tower)',
    category: 'PSU',
    brand: 'antec',
    price: 'Rp 590,000',
    picture: 'Antec VP Series 500W.png',
  },
  {
    itemId: 146,
    name: 'Patriot Burst 240GB',
    casing: 'all (mid-tower & tower)',
    category: 'hard disk',
    brand: 'patriot',
    price: 'Rp 813,000',
    picture: 'Patriot Burst 240GB.png',
  },
  {
    itemId: 147,
    name: 'NZXT H230 (Black / White)',
    casing: 'all (mid-tower & tower)',
    category: 'casing',
    brand: 'nzxt',
    price: 'Rp 1,250,000',
    picture: 'NZXT H230 (Black  White).png',
  },
  {
    itemId: 148,
    name: 'AMD Ryzen 5 2600',
    casing: 'all (mid-tower & tower)',
    category: 'proccesor',
    brand: 'amd',
    price: 'Rp 2,970,000',
    picture: 'AMD Ryzen 5 2600.png',
  },
  {
    itemId: 149,
    name: 'ASUS Prime x740-pro',
    casing: 'all (mid-tower & tower)',
    category: 'motherboard',
    brand: 'asus',
    price: 'Rp 3,545,000',
    picture: 'ASUS Prime x740-pro.png',
  },
  {
    itemId: 150,
    name: 'Gskill DDR4 RipjawsV PC19200 8GB (2x4GB)',
    casing: 'all (mid-tower & tower)',
    category: 'RAM',
    brand: 'gskill',
    price: 'Rp 1,237,000',
    picture: 'Gskill DDR4 RipjawsV PC19200 8GB (2x4GB).png',
  },
  {
    itemId: 151,
    name: 'Sapphire RX 570 4GB DDR5',
    casing: 'all (mid-tower & tower)',
    category: 'VGA',
    brand: 'sapphire',
    price: 'Rp 2,920,000',
    picture: 'Sapphire RX 570 4GB DDR5.png',
  },
  {
    itemId: 152,
    name: 'Seasonic Focus Gold 550GC',
    casing: 'all (mid-tower & tower)',
    category: 'PSU',
    brand: 'seasonic',
    price: 'Rp 1,150,000',
    picture: 'Seasonic Focus Gold 550GC.png',
  },
  {
    itemId: 153,
    name: 'Samsung SSD 860 EVO 500GB',
    casing: 'all (mid-tower & tower)',
    category: 'hard disk',
    brand: 'samsung',
    price: 'Rp 1,360,000',
    picture: 'Samsung SSD 860 EVO 500GB.png',
  },
  {
    itemId: 154,
    name: 'Fractal Meshify C TG (Black/White)',
    casing: 'tower',
    category: 'casing',
    brand: 'fractal',
    price: 'Rp 1,700,000',
    picture: 'Fractal Meshify C TG (BlackWhite).png',
  },
  {
    itemId: 155,
    name: 'AMD Ryzen 7 2700 .2Ghz Up To 4.1Ghz Cache 16MB',
    casing: 'all (mid-tower & tower)',
    category: 'proccesor',
    brand: 'amd',
    price: 'Rp 4,940,000',
    picture: 'AMD Ryzen 7 2700 .2Ghz Up To 4.1Ghz Cache 16MB.png',
  },
  {
    itemId: 156,
    name: 'ASRock B450 Pro 4',
    casing: 'tower',
    category: 'motherboard',
    brand: 'asrock',
    price: 'Rp 1,480,000',
    picture: 'ASRock B450 Pro 4.png',
  },
  {
    itemId: 157,
    name: 'Gigabyte GeForce GTX 1080 8GB DDR5 G1 Gaming',
    casing: 'all (mid-tower & tower)',
    category: 'VGA',
    brand: 'gigabyte',
    price: 'Rp 8,860,000',
    picture: 'Gigabyte GeForce GTX 1080 8GB DDR5 G1 Gaming.png',
  },
  {
    itemId: 158,
    name: 'Seasonic G-650 650W',
    casing: 'all (mid-tower & tower)',
    category: 'PSU',
    brand: 'seasonic',
    price: 'Rp 671,000',
    picture: 'Seasonic G-650 650W.png',
  },
  {
    itemId: 159,
    name: 'Crucial BX200 Hard Disk [480 GB]',
    casing: 'all (mid-tower & tower)',
    category: 'hard disk',
    brand: 'crucial',
    price: 'Rp 1,250,000',
    picture: 'Crucial BX200 Hard Disk [480 GB].png',
  },
  {
    itemId: 160,
    name: 'ASUS zephyrus gx501',
    casing: '-',
    category: 'laptop',
    brand: 'asus',
    price: 'Rp 29,905,000',
    picture: 'ASUS zephyrus gx501.png',
  },
];
