// flow-typed signature: ab43b43e4130c4e5e597425299210ffb
// flow-typed version: <<STUB>>/@feathersjs/authentication_v^2.1.12/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@feathersjs/authentication'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@feathersjs/authentication' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@feathersjs/authentication/coverage/block-navigation' {
  declare module.exports: any;
}

declare module '@feathersjs/authentication/coverage/lcov-report/block-navigation' {
  declare module.exports: any;
}

declare module '@feathersjs/authentication/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module '@feathersjs/authentication/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module '@feathersjs/authentication/coverage/prettify' {
  declare module.exports: any;
}

declare module '@feathersjs/authentication/coverage/sorter' {
  declare module.exports: any;
}

declare module '@feathersjs/authentication/lib/express/authenticate' {
  declare module.exports: any;
}

declare module '@feathersjs/authentication/lib/express/emit-events' {
  declare module.exports: any;
}

declare module '@feathersjs/authentication/lib/express/expose-cookies' {
  declare module.exports: any;
}

declare module '@feathersjs/authentication/lib/express/expose-headers' {
  declare module.exports: any;
}

declare module '@feathersjs/authentication/lib/express/failure-redirect' {
  declare module.exports: any;
}

declare module '@feathersjs/authentication/lib/express/index' {
  declare module.exports: any;
}

declare module '@feathersjs/authentication/lib/express/set-cookie' {
  declare module.exports: any;
}

declare module '@feathersjs/authentication/lib/express/success-redirect' {
  declare module.exports: any;
}

declare module '@feathersjs/authentication/lib/hooks/authenticate' {
  declare module.exports: any;
}

declare module '@feathersjs/authentication/lib/hooks/index' {
  declare module.exports: any;
}

declare module '@feathersjs/authentication/lib/index' {
  declare module.exports: any;
}

declare module '@feathersjs/authentication/lib/options' {
  declare module.exports: any;
}

declare module '@feathersjs/authentication/lib/passport/authenticate' {
  declare module.exports: any;
}

declare module '@feathersjs/authentication/lib/passport/index' {
  declare module.exports: any;
}

declare module '@feathersjs/authentication/lib/passport/initialize' {
  declare module.exports: any;
}

declare module '@feathersjs/authentication/lib/service' {
  declare module.exports: any;
}

declare module '@feathersjs/authentication/lib/socket/handler' {
  declare module.exports: any;
}

declare module '@feathersjs/authentication/lib/socket/index' {
  declare module.exports: any;
}

declare module '@feathersjs/authentication/lib/socket/update-entity' {
  declare module.exports: any;
}

declare module '@feathersjs/authentication/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module '@feathersjs/authentication/coverage/block-navigation.js' {
  declare module.exports: $Exports<'@feathersjs/authentication/coverage/block-navigation'>;
}
declare module '@feathersjs/authentication/coverage/lcov-report/block-navigation.js' {
  declare module.exports: $Exports<'@feathersjs/authentication/coverage/lcov-report/block-navigation'>;
}
declare module '@feathersjs/authentication/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'@feathersjs/authentication/coverage/lcov-report/prettify'>;
}
declare module '@feathersjs/authentication/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'@feathersjs/authentication/coverage/lcov-report/sorter'>;
}
declare module '@feathersjs/authentication/coverage/prettify.js' {
  declare module.exports: $Exports<'@feathersjs/authentication/coverage/prettify'>;
}
declare module '@feathersjs/authentication/coverage/sorter.js' {
  declare module.exports: $Exports<'@feathersjs/authentication/coverage/sorter'>;
}
declare module '@feathersjs/authentication/lib/express/authenticate.js' {
  declare module.exports: $Exports<'@feathersjs/authentication/lib/express/authenticate'>;
}
declare module '@feathersjs/authentication/lib/express/emit-events.js' {
  declare module.exports: $Exports<'@feathersjs/authentication/lib/express/emit-events'>;
}
declare module '@feathersjs/authentication/lib/express/expose-cookies.js' {
  declare module.exports: $Exports<'@feathersjs/authentication/lib/express/expose-cookies'>;
}
declare module '@feathersjs/authentication/lib/express/expose-headers.js' {
  declare module.exports: $Exports<'@feathersjs/authentication/lib/express/expose-headers'>;
}
declare module '@feathersjs/authentication/lib/express/failure-redirect.js' {
  declare module.exports: $Exports<'@feathersjs/authentication/lib/express/failure-redirect'>;
}
declare module '@feathersjs/authentication/lib/express/index.js' {
  declare module.exports: $Exports<'@feathersjs/authentication/lib/express/index'>;
}
declare module '@feathersjs/authentication/lib/express/set-cookie.js' {
  declare module.exports: $Exports<'@feathersjs/authentication/lib/express/set-cookie'>;
}
declare module '@feathersjs/authentication/lib/express/success-redirect.js' {
  declare module.exports: $Exports<'@feathersjs/authentication/lib/express/success-redirect'>;
}
declare module '@feathersjs/authentication/lib/hooks/authenticate.js' {
  declare module.exports: $Exports<'@feathersjs/authentication/lib/hooks/authenticate'>;
}
declare module '@feathersjs/authentication/lib/hooks/index.js' {
  declare module.exports: $Exports<'@feathersjs/authentication/lib/hooks/index'>;
}
declare module '@feathersjs/authentication/lib/index.js' {
  declare module.exports: $Exports<'@feathersjs/authentication/lib/index'>;
}
declare module '@feathersjs/authentication/lib/options.js' {
  declare module.exports: $Exports<'@feathersjs/authentication/lib/options'>;
}
declare module '@feathersjs/authentication/lib/passport/authenticate.js' {
  declare module.exports: $Exports<'@feathersjs/authentication/lib/passport/authenticate'>;
}
declare module '@feathersjs/authentication/lib/passport/index.js' {
  declare module.exports: $Exports<'@feathersjs/authentication/lib/passport/index'>;
}
declare module '@feathersjs/authentication/lib/passport/initialize.js' {
  declare module.exports: $Exports<'@feathersjs/authentication/lib/passport/initialize'>;
}
declare module '@feathersjs/authentication/lib/service.js' {
  declare module.exports: $Exports<'@feathersjs/authentication/lib/service'>;
}
declare module '@feathersjs/authentication/lib/socket/handler.js' {
  declare module.exports: $Exports<'@feathersjs/authentication/lib/socket/handler'>;
}
declare module '@feathersjs/authentication/lib/socket/index.js' {
  declare module.exports: $Exports<'@feathersjs/authentication/lib/socket/index'>;
}
declare module '@feathersjs/authentication/lib/socket/update-entity.js' {
  declare module.exports: $Exports<'@feathersjs/authentication/lib/socket/update-entity'>;
}
declare module '@feathersjs/authentication/lib/utils.js' {
  declare module.exports: $Exports<'@feathersjs/authentication/lib/utils'>;
}
