// flow-typed signature: 76b19650d89cb774df329791d1a1b4e6
// flow-typed version: <<STUB>>/@feathersjs/authentication-local_v^1.2.6/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@feathersjs/authentication-local'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@feathersjs/authentication-local' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@feathersjs/authentication-local/lib/hooks/hash-password' {
  declare module.exports: any;
}

declare module '@feathersjs/authentication-local/lib/hooks/index' {
  declare module.exports: any;
}

declare module '@feathersjs/authentication-local/lib/hooks/protect' {
  declare module.exports: any;
}

declare module '@feathersjs/authentication-local/lib/index' {
  declare module.exports: any;
}

declare module '@feathersjs/authentication-local/lib/utils/hash' {
  declare module.exports: any;
}

declare module '@feathersjs/authentication-local/lib/verifier' {
  declare module.exports: any;
}

// Filename aliases
declare module '@feathersjs/authentication-local/lib/hooks/hash-password.js' {
  declare module.exports: $Exports<'@feathersjs/authentication-local/lib/hooks/hash-password'>;
}
declare module '@feathersjs/authentication-local/lib/hooks/index.js' {
  declare module.exports: $Exports<'@feathersjs/authentication-local/lib/hooks/index'>;
}
declare module '@feathersjs/authentication-local/lib/hooks/protect.js' {
  declare module.exports: $Exports<'@feathersjs/authentication-local/lib/hooks/protect'>;
}
declare module '@feathersjs/authentication-local/lib/index.js' {
  declare module.exports: $Exports<'@feathersjs/authentication-local/lib/index'>;
}
declare module '@feathersjs/authentication-local/lib/utils/hash.js' {
  declare module.exports: $Exports<'@feathersjs/authentication-local/lib/utils/hash'>;
}
declare module '@feathersjs/authentication-local/lib/verifier.js' {
  declare module.exports: $Exports<'@feathersjs/authentication-local/lib/verifier'>;
}
