// flow-typed signature: bc6f74a7021808dcf31ea59cda02732a
// flow-typed version: <<STUB>>/@feathersjs/authentication-jwt_v^2.0.6/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@feathersjs/authentication-jwt'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@feathersjs/authentication-jwt' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@feathersjs/authentication-jwt/lib/index' {
  declare module.exports: any;
}

declare module '@feathersjs/authentication-jwt/lib/verifier' {
  declare module.exports: any;
}

// Filename aliases
declare module '@feathersjs/authentication-jwt/lib/index.js' {
  declare module.exports: $Exports<'@feathersjs/authentication-jwt/lib/index'>;
}
declare module '@feathersjs/authentication-jwt/lib/verifier.js' {
  declare module.exports: $Exports<'@feathersjs/authentication-jwt/lib/verifier'>;
}
