// flow-typed signature: b4b636d693902294e6d7e8441417862c
// flow-typed version: <<STUB>>/@feathersjs/configuration_v^2.0.4/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@feathersjs/configuration'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@feathersjs/configuration' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@feathersjs/configuration/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@feathersjs/configuration/lib/index.js' {
  declare module.exports: $Exports<'@feathersjs/configuration/lib/index'>;
}
