// flow-typed signature: 56a3d05862a052009f070bd63862b716
// flow-typed version: <<STUB>>/@feathersjs/errors_v^3.3.4/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@feathersjs/errors'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@feathersjs/errors' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@feathersjs/errors/handler' {
  declare module.exports: any;
}

declare module '@feathersjs/errors/lib/error-handler' {
  declare module.exports: any;
}

declare module '@feathersjs/errors/lib/index' {
  declare module.exports: any;
}

declare module '@feathersjs/errors/lib/not-found-handler' {
  declare module.exports: any;
}

declare module '@feathersjs/errors/not-found' {
  declare module.exports: any;
}

// Filename aliases
declare module '@feathersjs/errors/handler.js' {
  declare module.exports: $Exports<'@feathersjs/errors/handler'>;
}
declare module '@feathersjs/errors/lib/error-handler.js' {
  declare module.exports: $Exports<'@feathersjs/errors/lib/error-handler'>;
}
declare module '@feathersjs/errors/lib/index.js' {
  declare module.exports: $Exports<'@feathersjs/errors/lib/index'>;
}
declare module '@feathersjs/errors/lib/not-found-handler.js' {
  declare module.exports: $Exports<'@feathersjs/errors/lib/not-found-handler'>;
}
declare module '@feathersjs/errors/not-found.js' {
  declare module.exports: $Exports<'@feathersjs/errors/not-found'>;
}
