// flow-typed signature: d97ab767a97d4ba40a199f310b6cda74
// flow-typed version: <<STUB>>/@feathersjs/express_v^1.2.7/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@feathersjs/express'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@feathersjs/express' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@feathersjs/express/errors' {
  declare module.exports: any;
}

declare module '@feathersjs/express/lib/index' {
  declare module.exports: any;
}

declare module '@feathersjs/express/lib/rest/index' {
  declare module.exports: any;
}

declare module '@feathersjs/express/lib/rest/wrappers' {
  declare module.exports: any;
}

declare module '@feathersjs/express/rest' {
  declare module.exports: any;
}

// Filename aliases
declare module '@feathersjs/express/errors.js' {
  declare module.exports: $Exports<'@feathersjs/express/errors'>;
}
declare module '@feathersjs/express/lib/index.js' {
  declare module.exports: $Exports<'@feathersjs/express/lib/index'>;
}
declare module '@feathersjs/express/lib/rest/index.js' {
  declare module.exports: $Exports<'@feathersjs/express/lib/rest/index'>;
}
declare module '@feathersjs/express/lib/rest/wrappers.js' {
  declare module.exports: $Exports<'@feathersjs/express/lib/rest/wrappers'>;
}
declare module '@feathersjs/express/rest.js' {
  declare module.exports: $Exports<'@feathersjs/express/rest'>;
}
