// flow-typed signature: 52a3d4772f38b0935326154ab16ab60a
// flow-typed version: <<STUB>>/@feathersjs/socketio_v^3.2.7/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@feathersjs/socketio'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@feathersjs/socketio' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@feathersjs/socketio/client' {
  declare module.exports: any;
}

declare module '@feathersjs/socketio/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@feathersjs/socketio/client.js' {
  declare module.exports: $Exports<'@feathersjs/socketio/client'>;
}
declare module '@feathersjs/socketio/lib/index.js' {
  declare module.exports: $Exports<'@feathersjs/socketio/lib/index'>;
}
